[tool.pixi.feature.dev.dependencies]
pdoc = "*"
tomli = "*"

[tool.pixi.tasks]
gen-doc = "pdoc --html --output-dir docs src"
serve-doc = "pdoc --http : src"

[tool.pyscaf.documentation]
output_path = "docs"