# Jupyter Tools Configuration

[tool.pyscaf.jupyter-tools]
# Default output directories
python_notebook_dir = "notebooks/python"
jupyter_notebook_dir = "notebooks/ipynb"
pdf_dir = "generated/pdfs"
html_dir = "generated/html"

[project.scripts]
# Convenient scipts
py-to-nb = "jupyter_tools.py_to_notebook:main"
exec-nb = "jupyter_tools.execute_notebook:main"
nb-to-html = "jupyter_tools.notebook_to_html:main"

[tool.poetry.group.dev.dependencies]
jupytext = "*"
nbconvert = "*"
# weasyprint = "*"
# pandoc = "*"
