name: Deploy to Production PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    uses: ./.github/workflows/reusable-deploy.yml
    permissions:
      contents: write
      id-token: write
    with:
      environment: production
      pypi_repository_url: 'https://upload.pypi.org/legacy/'
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }} 