name: Deploy to Production PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: production
      pypi_repository_url: 'https://upload.pypi.org/legacy/'
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 