name: Deploy to TestPyPI

on:
  push:
    branches:
      - develop

jobs:
  deploy-test:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: test
      pypi_repository_url: 'https://test.pypi.org/legacy/'
    secrets:
      PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 