name: Deploy to TestPyPI

on:
  push:
    branches:
      - develop

jobs:
  deploy-test:
    uses: ./.github/workflows/reusable-deploy.yml
    permissions:
      contents: write
      id-token: write
    with:
      environment: test
      pypi_repository_url: 'https://test.pypi.org/legacy/'
    secrets:
      PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }} 