name: Sync main to GitLab (SSH)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan forge.inrae.fr >> ~/.ssh/known_hosts

      - name: Push to GitLab
        env:
          GITLAB_REPO_SSH: ${{ secrets.GITLAB_REPO_SSH }}
        run: |
          git config --global user.email "guilhem.heinrich@gmail.com"
          git config --global user.name "GitHub Actions"
          git remote add gitlab "$GITLAB_REPO_SSH"
          git push --force gitlab main:main 